from flask import Blueprint,render_template,request,redirect,session
from flask.helpers import url_for
from flask_login import current_user
from flask_sqlalchemy import SQLAlchemy
from .auth import login, logout,sign_up
#potential error with duplicate names for getTable
from .scraperReader import ReadData,getTableData,getTable as makeTable,tableSplit
from flask_login import logout_user
import requests
from requests_html import HTMLSession
from . import db
import datetime
from .models import User,Major,Table
from .makeList import add,getList,setList
from .printDB import printDB
import json


views = Blueprint('views', __name__)

now = datetime.datetime.now()
def createMajors():
    from .models import Major
    majors = ['אלקטרוניקה','דיפלומטיה','כימיה','אומנות','מוסיקה','פיזיקה','מדעי המחשב','ביולוגיה','תיירות']

    if len(Major.query.all())!=len(majors):
        db.session.query(Major).delete()

        for major in majors:
            create_major(major)
        db.session.commit()
    

def create_major(name):
    major = Major(name=name,keywords=name)
    db.session.add(major)

@views.route('/main', methods=['GET'])
def main():
    return render_template("main.html")



@views.route('/', methods=['GET'])
def home(): 
    createMajors()    
    if not current_user.is_authenticated:
        return redirect('/welcome')
   
    lstKeyWords=[]
    
    if 'major' in session and session['major']!=None:
        major=Major.query.filter_by(name=session['major']).first()
        lstKeyWords=getList(major.keywords)

    table=None
  
    if current_user.last_date=='':
        current_user.last_date=str(now.month)+"/"+str(now.year)
        table = createTable(current_user.last_date,True)       
    else:
        #This means the table exists, and it hasn't been regenerated by the user. Whenever the user regenerated a tables a ; is added to last date
        if current_user.last_date.find(';')!=-1:
            current_user.last_date = current_user.last_date.replace(';','')
            table = createTable(current_user.last_date,True)   
        if current_user.last_date.find(']')!=-1:
            current_user.last_date = current_user.last_date.replace(']','')
            table = createTable(current_user.last_date,False)   
        #This means the table exists, and it hasn't been deleted by the user. Whenever the user deleted a tables a : is added to last date
        if current_user.last_date.find(':')!=-1:
            current_user.last_date = current_user.last_date.replace(':','')
            table = createBlankTable(current_user.last_date)
        else:
            table = getTable(current_user.last_date)     


   
    nowMonth=False
    if int(table.date.split('/')[0]) == now.month:
        nowMonth=True
    printDB()

    return render_template("main.html",user=current_user,table=table,Major=Major,getList=getList,getMajors=getMajors,lstKeyWords=lstKeyWords,nowMonth=nowMonth)

def createTable(date,check):
    split = date.split('/')
    table = ReadData(int(split[0]),int(split[1]),check)
    
    newTable = Table(table=table,date=date,userId=current_user.id)
    db.session.add(newTable)
    current_user.tables.append(newTable)

    db.session.commit()
    print("table has been created")
    return newTable

def createBlankTable(date):     
    split = date.split('/')
    table_data = getTableData(int(split[0]),int(split[1]))

    table_html = makeTable(table_data.getList())
    newTable = Table(table=table_html,date=date,userId=current_user.id)
    db.session.add(newTable)
    current_user.tables.append(newTable)
    db.session.commit()
    print("blank table has been created")

    return newTable

def getMajors(id,addSelect):
    majors_obj = Major.query.all()
    majors=[]
    for major in majors_obj:
        majors.append(major.name)

    select=id

    if addSelect:
        select+='<option value="Select" style="display:none;">בחר מגמה</option>'

    for major in Major.query.all():        
        select += '\n'+'<option value={1}{0}{1}>{0}</option>'.format(major.name,'"')
    select+="\n"+"</select>"
    return select

def getTable(date):
    tables = current_user.tables
    table = None

    for table_user in tables:
        if date==table_user.date:
            return table_user
    return table


@views.route('/removeKeyWord',methods=['POST'])
def removeKeyWord():
    keyword=request.form['keyword']
    if session['major'] == "select":
        return ""
    major=Major.query.filter_by(name=session['major']).first()

    lst_keywords = getList(major.keywords)
    lst_keywords.remove(keyword)
    major.keywords=setList(lst_keywords)
    session['major'] = None
    db.session.commit()

    return ""   


@views.route('/selectKeyWord',methods=['POST'])
def selectKeyWord():
    major_name=request.form.get('selectKeyWordSelect')

    major=Major.query.filter_by(name=major_name).first()
    session['major']=major.name


    return redirect('/')

@views.route('/addKeyWord',methods=['POST'])
def addKeyWord():
    major_name=request.form.get('addKeyWordSelect')
    print(major_name)
    if major_name != 'Select':
        keyword= request.form.get('addKeyWordtxt')
        major=Major.query.filter_by(name=major_name).first()
        major.keywords=add(major.keywords,keyword)
        db.session.commit()

    return redirect('/')

@views.route('/regenerateTable',methods=['POST'])
def regenerateTable():
    table_id = request.form.get('table_id')

    

    table = Table.query.get(table_id)
    current_user.last_date+=';'
    db.session.delete(Table.query.get(table_id))
    db.session.commit()
    
    

    return redirect('/')

@views.route('/regenerateTableNoFilter',methods=['POST'])
def regenerateTableNoFilter():
    table_id = request.form.get('table_id')
    table = Table.query.get(table_id)
    current_user.last_date+=']'
    db.session.delete(table)
    db.session.commit()
    return redirect('/')

@views.route('/deleteTable',methods=['POST'])
def deleteTable():
    table_id = request.form.get('table_id')
    table = Table.query.get(table_id)
    current_user.last_date+=':'
    db.session.delete(table)
    db.session.commit()
    return redirect('/')

@views.route('/rightArrow', methods=['POST'])
def rightArrow():
    table_date = request.form.get('table_date2')
    
    split = table_date.split('/')
    month = int(split[0])
    year = int(split[1])

    if month>1:
        date = str(month-1)+"/"+str(year)

        table = getTable(date)
        if table:            
            current_user.last_date=date
            db.session.commit()
        else:
            createTable(date,True)
            current_user.last_date=date
            db.session.commit()
    elif year==now.year:
        print("month from last year")
        #month from last year, prompt the user of this    
    else:
        date = str(12)+"/"+str(year-1)
        table = getTable(date)
        if table:            
            current_user.last_date=date
            db.session.commit()
        else:
            createTable(date,True)
            current_user.last_date=date
            db.session.commit()


    return redirect('/')

@views.route('/leftArrow', methods=['POST'])
def leftArrow():
    table_date = request.form.get('table_date1')
    print(table_date)
    split = table_date.split('/')
    month = int(split[0])
    year = int(split[1])
    date = str(month+1)+"/"+str(year)

    if month<12:
        table = getTable(date)
        if table:            
            current_user.last_date=date
            db.session.commit()
        else:
            createTable(date,True)
            current_user.last_date=date
            db.session.commit()
    else:
        if year>now.year:
            print("2023 chill")        
        else:
            date = str(1)+"/"+str(year+1)
            createTable(date,True)
            current_user.last_date=date
            db.session.commit()

    return redirect('/')

@views.route('/updateTable', methods = ['POST'])
def UpdateTable():
    jsdata = request.form['javascript_data']
    date = request.form['date']
    if len(jsdata.split(tableSplit))>1:

        table = jsdata.split(tableSplit)[1]
        table = tableSplit+table
        table = table.split('</table>')[0]
        table+= '</table>'

        existing_table = getTable(date)
        if existing_table:
            existing_table.table=table
            db.session.commit()

        


    return ""

@views.route('/addMajor', methods=['POST'])
def add_Major_To_db():
    jsdata = request.form.get('selectMajor')
    if jsdata=="Select": 
        print("lol")
        return redirect('/')
    major = Major.query.filter_by(name=jsdata).first()


    current_user.majors=add(current_user.majors,major.id)
    db.session.commit()
    return redirect('/')

@views.route('/deleteMajor', methods=['POST'])
def deleteMajor():
    jsdata = request.form['javascript_data']
    lst :list= getList(current_user.majors)
    lst.remove(jsdata)
    current_user.majors=setList(lst)
    db.session.commit()
    return ""

@views.route('/welcome', methods=['GET','POST'])
def welcome():   
    createMajors()

   
    if current_user.is_authenticated:
        return redirect('/')

    if request.method == "POST":        
        if request.form.get("sign-up"):
            return sign_up()
        elif request.form.get("login"):
            return login()
    
    return render_template("index.html",user=current_user)





     



    
  
  
   



